#include "BuckApp.h"
#include "Moose.h"
#include "AppFactory.h"
#include "BuckRevision.h" // This file is autogenerated and contains the revision.

// Auxkernels

// Kernels
#include "VariableScaledSource.h"
#include "HomNucleation.h"
#include "SpeciesDiffusion.h"

// Materials
#include "HomNucleationMaterial.h"

// Postprocessors
#include "GrainBoundaryGasFlux.h"
#include "SumOfPostprocessors.h"

// User Objects


template<>
InputParameters validParams<BuckApp>()
{
  InputParameters params = validParams<MooseApp>();
  return params;
}

BuckApp::BuckApp(const std::string & name, InputParameters parameters) :
    MooseApp(name, parameters)
{
  srand(processor_id());

  Moose::registerObjects(_factory);
  BuckApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  BuckApp::associateSyntax(_syntax, _action_factory);
}

BuckApp::~BuckApp()
{
}

void
BuckApp::registerApps()
{
  registerApp(BuckApp);
}

void
BuckApp::registerObjects(Factory & factory)
{
  registerKernel(VariableScaledSource);
  registerKernel(HomNucleation);
  registerKernel(SpeciesDiffusion);

  registerMaterial(HomNucleationMaterial);

  registerPostprocessor(GrainBoundaryGasFlux);
  registerPostprocessor(SumOfPostprocessors);
}

void
BuckApp::associateSyntax(Syntax & syntax, ActionFactory & action_factory)
{
}

void
BuckApp::runInputFile()
{
  printHeader();
  MooseApp::runInputFile();
}

void
BuckApp::printHeader()
{
  Moose::out  << "\n"
              << "\n"
              << "     ______  _     _  ______ _    _      \n"
              << "    (____  \\| |   | |/ _____) |  / )    \n"
              << "     ____)  ) |   | | /     | | / /      \n"
              << "    |  __  (| |   | | |     | |< <       \n"
              << "    | |__)  ) |___| | \\_____| | \\ \\   \n"
              << "    |______/ \\______|\\______)_|  \\_)  \n"
                                
              << "\n"
              << "\n"
              << "      Bubble and Cluster Kinetics \n"
              << "        Oregon State University   \n"
              << "             Corvallis, OR        \n"
              << "\n"
              << "\n";
              
  Moose::out << "Input file:   " << _input_filename << "\n"
             << "Input units:  nanometer, gram, second, kelvin, mole\n"
             << "\n"
             << "BUCK version: " << BUCK_REVISION << std::endl
             << std::endl;
}
