#include "BuckApp.h"
#include "Moose.h"
#include "AppFactory.h"
#include "BuckRevision.h" // This file is autogenerated and contains the revision.

// Modules
#include "ContactApp.h"
#include "HeatConductionApp.h"
#include "LinearElasticityApp.h"
#include "MiscApp.h"
#include "SolidMechanicsApp.h"
// #include "TensorMechanicsApp.h"
// #include "PhaseFieldApp.h"
// #include "ChemicalReactionsApp.h"

#include "BisonApp.h"
#include "BisonSyntax.h"

// #include "MarmotApp.h"
// #include "MarmotSyntax.h"

// Auxkernels
#include "PorosityAuxUC.h"
#include "PorosityAuxUr.h"

// Kernels
#include "VariableScaledSource.h"
#include "HomClusterCombination.h"
#include "HomPointLoss.h"
#include "HomClusterLoss.h"

// Materials
#include "ThermalUC.h"
#include "CreepUC.h"
#include "MechUC.h"
#include "VSwellingUC.h"
#include "VSwellingUr.h"
#include "UrFGR.h"
#include "ZonalUC.h"
#include "HomNucleationMaterial.h"

//Postprocessors
#include "RatioPostprocessor.h"

// User Objects
#include "BubbleAtomicDensityUO.h"



template<>
InputParameters validParams<BuckApp>()
{
  InputParameters params = validParams<MooseApp>();
  return params;
}

BuckApp::BuckApp(const std::string & name, InputParameters parameters) :
    MooseApp(name, parameters)
{
  srand(processor_id());

  Moose::registerObjects(_factory);
  BuckApp::registerObjects(_factory);
  
  ContactApp::registerObjects(_factory);
  HeatConductionApp::registerObjects(_factory);
  LinearElasticityApp::registerObjects(_factory);
  MiscApp::registerObjects(_factory);
  SolidMechanicsApp::registerObjects(_factory);
  BisonApp::registerObjects(_factory);
  // MarmotApp::registerObjects(_factory);
  // PhaseFieldApp::registerObjects(_factory);
  // TensorMechanicsApp::registerObjects(_factory);
  // ChemicalReactionsApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  BuckApp::associateSyntax(_syntax, _action_factory);
  
  ContactApp::associateSyntax(_syntax, _action_factory);
  HeatConductionApp::associateSyntax(_syntax, _action_factory);
  MiscApp::associateSyntax(_syntax, _action_factory);
  SolidMechanicsApp::associateSyntax(_syntax, _action_factory);
  Bison::associateSyntax(_syntax, _action_factory);
  // Marmot::associateSyntax(_syntax, _action_factory);
  // PhaseFieldApp::associateSyntax(_syntax, _action_factory);
  // TensorMechanicsApp::associateSyntax(_syntax, _action_factory);
  // ChemicalReactionsApp::associateSyntax(_syntax, _action_factory);
}

BuckApp::~BuckApp()
{
}

void
BuckApp::registerApps()
{
  registerApp(BuckApp);
}

void
BuckApp::registerObjects(Factory & factory)
{
  registerAux(PorosityAuxUC);
  registerAux(PorosityAuxUr);

  registerKernel(VariableScaledSource);
  registerKernel(HomClusterCombination);
  registerKernel(HomPointLoss);
  registerKernel(HomClusterLoss);
  
  registerMaterial(ThermalUC);
  registerMaterial(CreepUC);
  registerMaterial(VSwellingUC);
  registerMaterial(VSwellingUr);
  registerMaterial(MechUC);
  registerMaterial(UrFGR);
  registerMaterial(ZonalUC);
  registerMaterial(HomNucleationMaterial);

  registerPostprocessor(RatioPostprocessor);

  registerUserObject(BubbleAtomicDensityUO);
}

void
BuckApp::associateSyntax(Syntax & syntax, ActionFactory & action_factory)
{
}

void
BuckApp::runInputFile()
{
  printHeader();
  MooseApp::runInputFile();
}

void
BuckApp::printHeader()
{
  Moose::out  << "\n"
              << "\n"
              << "     ______  _     _  ______ _    _      \n"
              << "    (____  \\| |   | |/ _____) |  / )    \n"
              << "     ____)  ) |   | | /     | | / /      \n"
              << "    |  __  (| |   | | |     | |< <       \n"
              << "    | |__)  ) |___| | \\_____| | \\ \\   \n"
              << "    |______/ \\______|\\______)_|  \\_)  \n"
                                
              << "\n"
              << "\n"
              << "      Bubble and Cluster Kinetics \n"
              << "        Oregon State University   \n"
              << "             Corvallis, OR        \n"
              << "\n"
              << "\n";
  if (_argv)
  {
    std::string argv(_argv[0]);
    for (int i = 1; i < _argc; ++i)
    {
      argv += " ";
      argv += std::string(_argv[i]);
    }
    Moose::out << "Command line: " << argv << "\n";
  }
  Moose::out << "Input file:   " << _input_filename << "\n"
             << "Input units:  nanometer, gram, second, kelvin, mole\n"
             << "\n"
             << "BUCK version: " << BUCK_REVISION << std::endl
             << std::endl;
}
